# Colors
GREEN="\033[1;32m"
RED="\033[1;31m"
WHITE="\033[1;97m"
CYAN="\033[1;36m"
FAINT="\033[2m"

# Flags
export FLAG_OPEN="${FLAG_OPEN:-🔲}"
export FLAG_COMPLETED="${FLAG_COMPLETED:-✅}"
export FLAG_JOURNAL="${FLAG_JOURNAL:-📘}"
export FLAG_NOTE="${FLAG_NOTE:-🗒️}"
export FLAG_PRIORITY="${FLAG_PRIORITY:-❗}"
export FLAG_ATTACHMENT="${FLAG_ATTACHMENT:-🔗}"

# Style
export STYLE_COLLECTION="${STYLE_COLLECTION:-$FAINT$WHITE}"
export STYLE_DATE="${STYLE_DATE:-$CYAN}"
export STYLE_SUMMARY="${STYLE_SUMMARY:-$GREEN}"
export STYLE_EXPIRED="${STYLE_EXPIRED:-$RED}"
export STYLE_CATEGORY="${STYLE_CATEGORY:-$WHITE}"
